name: Spring Boot Dev CI

on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source
        uses: actions/checkout@v4


      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven


      - name: Build Maven Project
        run: mvn clean package


      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Generate Image Tags
        id: image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/springboot-poc

          SHA=$(git rev-parse --short HEAD)

          echo "IMAGE=$IMAGE" >> $GITHUB_OUTPUT
          echo "SHA=$SHA" >> $GITHUB_OUTPUT

          echo "Docker Image:"
          echo "$IMAGE"
          echo "Commit SHA:"
          echo "$SHA"


      - name: Build Dev Docker Image
        run: |
          IMAGE=${{ steps.image.outputs.IMAGE }}
          SHA=${{ steps.image.outputs.SHA }}

          docker build \
            -t $IMAGE:dev-latest \
            -t $IMAGE:dev-${{ github.run_number }} \
            -t $IMAGE:dev-$SHA .


      - name: Push Dev Docker Images
        run: |
          IMAGE=${{ steps.image.outputs.IMAGE }}
          SHA=${{ steps.image.outputs.SHA }}

          docker push $IMAGE:dev-latest
          docker push $IMAGE:dev-${{ github.run_number }}
          docker push $IMAGE:dev-$SHA


      - name: Display Published Images
        run: |
          IMAGE=${{ steps.image.outputs.IMAGE }}
          SHA=${{ steps.image.outputs.SHA }}

          echo "Published Dev Images:"
          echo "$IMAGE:dev-latest"
          echo "$IMAGE:dev-${{ github.run_number }}"
          echo "$IMAGE:dev-$SHA"